# Generated by Django 3.2.5 on 2022-06-30 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('accused', models.TextField(blank=True, null=True)),
                ('plaintiff', models.TextField(blank=True, null=True)),
                ('aditional_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('اندراج معاملہ', 'اندراج معاملہ'), ('اطلاع اول بنام فریق دوم مع مثنی  درخواست فریق اول', 'اطلاع اول بنام فریق دوم مع مثنی  درخواست فریق اول'), ('فریق دوم  کو اطلاع موصول ہوئی', 'فریق دوم  کو اطلاع موصول ہوئی'), ('فریق دوم کو اطلاع موصول نہیں ہوئی', 'فریق دوم کو اطلاع موصول نہیں ہوئی'), ('ادخال بیان تحریری من جانب فریق ثانی', 'ادخال بیان تحریری من جانب فریق ثانی'), ('اطلاع بنام فریق اول برائے طلبی پتہ فریق دوم و  متعلقین ومعززین فریق دوم', 'اطلاع بنام فریق اول برائے طلبی پتہ فریق دوم و  متعلقین ومعززین فریق دوم'), ('اطلاع ثانی بنام فریق دوم / متعلقین  و معززین فریق دوم مع مثنی درخواست', 'اطلاع ثانی بنام فریق دوم / متعلقین  و معززین فریق دوم مع مثنی درخواست'), ('تاریخ سماعت اول', 'تاریخ سماعت اول'), ('حاضری فریقین مع گواہان  و اندراج بیانات', 'حاضری فریقین مع گواہان  و اندراج بیانات'), ('حاضری فریق اول فقط مع گواہان واندراج بیانات', 'حاضری فریق اول فقط مع گواہان واندراج بیانات'), ('حاضری فریق دوم فقط مع گواہا ن و اندراج بیانات', 'حاضری فریق دوم فقط مع گواہا ن و اندراج بیانات'), ('ا طلاع ثالث بنام فریق دوم', 'ا طلاع ثالث بنام فریق دوم'), ('اشتہار مفقود الخبر ی در اخبار نقیب', 'اشتہار مفقود الخبر ی در اخبار نقیب'), ('تاریخ سماعت دوم', 'تاریخ سماعت دوم'), ('حاضری فریقین مع گواہان  و اندراج بیانات', 'حاضری فریقین مع گواہان  و اندراج بیانات'), ('حاضری فریق اول فقط مع گواہان واندراج بیانات', 'حاضری فریق اول فقط مع گواہان واندراج بیانات'), ('حاضری فریق دوم فقط مع گواہا ن و اندراج بیانات', 'حاضری فریق دوم فقط مع گواہا ن و اندراج بیانات'), ('تاریخ سماعت سوم', 'تاریخ سماعت سوم'), ('حاضری فریقین مع گواہان  و اندراج بیانات', 'حاضری فریقین مع گواہان  و اندراج بیانات'), ('حاضری فریق اول فقط مع گواہان واندراج بیانات', 'حاضری فریق اول فقط مع گواہان واندراج بیانات'), ('حاضری فریق دوم فقط مع گواہا ن و اندراج بیانات', 'حاضری فریق دوم فقط مع گواہا ن و اندراج بیانات'), ('تصفیہ', 'تصفیہ'), ('خارج بلا تجویز', 'خارج بلا تجویز'), ('مصالحت بذریعہ  خلع/ طلاق/ رخصتی', 'مصالحت بذریعہ  خلع/ طلاق/ رخصتی'), ('آخری حکم', 'آخری حکم'), ('ارسال مثل مرکزی دار القضاء', 'ارسال مثل مرکزی دار القضاء')], max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to='')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('law', 'law'), ('admin', 'admin')], max_length=100)),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditional_text', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='darul.case')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='darul.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('court', models.ManyToManyField(blank=True, to='darul.Court')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='darul.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='darul.casetype'),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='darul.court'),
        ),
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='darul.judge'),
        ),
    ]
