# Generated by Django 3.2.5 on 2022-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
