# Generated by Django 3.2.5 on 2022-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('lawyer', 'lawyer'), ('admin', 'admin')], max_length=100),
        ),
    ]
