# Generated by Django 3.2.5 on 2022-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('law', 'law'), ('admin', 'admin')], max_length=100),
        ),
    ]
