# Generated by Django 3.2.5 on 2022-06-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
