# Generated by Django 3.2.5 on 2022-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0007_auto_20220617_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='court',
        ),
        migrations.AddField(
            model_name='judge',
            name='court',
            field=models.ManyToManyField(blank=True, null=True, to='darul.Court'),
        ),
    ]
