# Generated by Django 3.2.5 on 2022-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0008_auto_20220617_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='court',
            field=models.ManyToManyField(blank=True, to='darul.Court'),
        ),
    ]
