# Generated by Django 3.2.5 on 2022-06-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0011_auto_20220618_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='judge',
        ),
        migrations.AddField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='darul.userprofile'),
        ),
    ]
