# Generated by Django 3.2.5 on 2022-06-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darul', '0012_auto_20220618_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='darul.case'),
        ),
    ]
